# Generated by Django 3.2.16 on 2024-01-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inductees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(default='000000000', max_length=9)),
                ('department', models.CharField(default='National Institute of Technology, Durgapur', max_length=50)),
                ('is_club_member', models.BooleanField(default=False)),
                ('profile_picture', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('year', models.IntegerField(default=1)),
                ('registration_no', models.CharField(blank=True, max_length=15)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('round', models.IntegerField(default=1)),
                ('color', models.IntegerField(choices=[(1, 'red'), (2, 'yellow'), (3, 'green'), (4, 'transparent')], default=4)),
                ('domains', models.CharField(blank=True, choices=[('WEBD', 'WEB DEVELOPEMENT'), ('VIDEO', 'VIDEO EDITING'), ('CONTENT', 'CONTENT WRITING'), ('EVENT', 'EVENT MANAGEMENT')], max_length=25)),
                ('like', models.ManyToManyField(related_name='vote', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'text'), ('range', 'range'), ('options', 'options')], default='text', max_length=10)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('inductee', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.inductees')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('round', models.IntegerField(default=1)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.inductees')),
            ],
            options={
                'ordering': ['-round', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.inductees')),
            ],
            options={
                'unique_together': {('student', 'question')},
            },
        ),
    ]
