# Generated by Django 3.2.16 on 2024-01-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('inductee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.inductees')),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
