# Generated by Django 3.2.16 on 2023-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
