# Generated by Django 3.2.16 on 2024-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductees',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inductees',
            name='registration_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='inductees',
            name='rollnumber',
            field=models.CharField(default='', max_length=9),
        ),
    ]
