# Generated by Django 3.2.16 on 2023-12-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='department',
            field=models.CharField(default='National Institute of Technology, Durgapur', max_length=50),
        ),
        migrations.AlterField(
            model_name='inductees',
            name='rollnumber',
            field=models.CharField(default='000000000', max_length=9, unique=True),
        ),
    ]
