# Generated by Django 3.2.16 on 2024-01-05 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=10),
        ),
        migrations.AddField(
            model_name='inductees',
            name='like',
            field=models.ManyToManyField(related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductees',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inductees',
            name='registration_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='inductees',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.inductees'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
