# Generated by Django 3.2.16 on 2023-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20231210_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductees',
            name='rollnumber',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
