# Generated by Django 3.2.16 on 2023-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_inductees_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inductees',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
