# Generated by Django 3.2.16 on 2023-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_response_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
