# Generated by Django 3.2.16 on 2023-12-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20231227_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='time',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
