# Generated by Django 3.2.16 on 2023-12-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20231210_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
