# Generated by Django 3.2.16 on 2023-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20231227_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inductees',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=10),
        ),
        migrations.AddField(
            model_name='inductees',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inductees',
            name='registration_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
