# Generated by Django 3.2.16 on 2023-12-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_inductees_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('round', models.IntegerField(default=1)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.inductees')),
            ],
            options={
                'ordering': ['-round', '-date'],
            },
        ),
    ]
