# Generated by Django 3.2.16 on 2023-12-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20231227_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductees',
            name='email',
        ),
    ]
