# Generated by Django 3.2.16 on 2023-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_inductees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
