# Generated by Django 3.2.16 on 2023-12-29 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0010_inductees_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductees',
            name='likes',
        ),
        migrations.AddField(
            model_name='inductees',
            name='like',
            field=models.ManyToManyField(related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
