# Generated by Django 3.2.16 on 2024-01-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20231229_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='color',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'yellow'), (3, 'green'), (4, 'transparent')], default=4),
        ),
    ]
